### PR TITLE
Replace "open-source" with "open source"

### LINKED ISSUE #508: open source - no dash

### PR DESCRIPTION
**Pull request by ryan-blunden**
Replace all instances of "open-source" in content to "open source" to fix #508

### CODE REVIEW

**Comment by sqs** [comment]
Let's conclude the discussion at https://github.com/sourcegraph/about/issues/508 before merging this.

**Comment by sqs** [comment]
- Document this rule in the style guide (https://github.com/sourcegraph/about/issues/508)

**Comment by ryan-blunden** [comment]
@sqs Rule has been added to the [specific terms in prose](https://github.com/sourcegraph/about/pull/584/files#diff-513611370726f43ae7d8f11c32ba9951R133) section.

**Comment by creachadair** [comment]
There's one more to fix at https://github.com/sourcegraph/about/blob/98708c957b4f1b0688e6e7490ff0b9900c6af7df/website/src/components/product/OpenSourcePrivacyFeatureItem.tsx#L8

Otherwise, well, I don't love it, but it does what it says on the tin.

**Comment by ryan-blunden** [comment]
Thanks for the catch @creachadair, I've pushed that change.

**Comment by ryan-blunden** [comment]
@sqs I'll wait for your approval before merging.

**Pull request merged**
