### PR TITLE
Fix Shift Left Video

### PR DESCRIPTION
**Pull request by zlonko**
This fixes a bug duplicating one of the videos in the blogpost. This was due to error transcribing the video path.

### Changelog
- Updates markdown with correct video

### Test

1. Ensure prettier has standardized the proposed changes.
2. Please check that the first and second videos are different.

### CODE REVIEW

**Comment by st0nebraker** [comment]
I don't see the backup videos rendering on Safari, do you @zlonko ?

**Comment by zlonko** [comment]
@st0nebraker I see the same. I am not sure why, though, because I was able to view the videos in Safari before shipping the original blogpost. It seems like reversing the order of the mp4 and webm videos gets them to appear in Safari: f99d86c. Do you see the same on staging?

**Review by st0nebraker — APPROVED** [review]
> @st0nebraker I see the same. I am not sure why, though, because I was able to view the videos in Safari before shipping the original blogpost. It seems like reversing the order of the mp4 and webm videos gets them to appear in Safari: [f99d86c](https://github.com/sourcegraph/about/commit/f99d86c1487d219ae29ec6229240946bbf662c99). Do you see the same on staging?

That's odd. The rearranged order seems to work on staging! Lets keep an eye on it after this ships. Thanks Tim ⭐

**Comment by bretthayes** [comment]
Just wanted to note the video element's sources are loaded in the order they are declared in. Here's [the spec for reference](https://html.spec.whatwg.org/multipage/media.html#media-element-load-algorithm:~:text=immediately%20resolve%20or%20reject%20those%20promises%20in%20the%20order%20the%20corresponding%20tasks%20were%20queued.). 🤓 Although mp4 is more widely supported than webm, it's weird that one or the other didn't get loaded as a fallback option? 🤔 

cc @zlonko @st0nebraker

**Pull request merged**
