### PR TITLE
Create mariam-readme.md

### PR DESCRIPTION
**Pull request by rhiam**

### CODE REVIEW

**Review by virginiaulrich — COMMENTED** [review]
You will also need to add your name to https://about.sourcegraph.com/handbook/support/support-bios with a link to this page ... otherwise, the checks will continue to fail. Every time you add a new page to the handbook, you must link to that new page from an existing page :)

**Comment by rhiam** [comment]
> You will also need to add your name to https://about.sourcegraph.com/handbook/support/support-bios with a link to this page ... otherwise, the checks will continue to fail. Every time you add a new page to the handbook, you must link to that new page from an existing page :)

I have added my name with the new link but the new commit is also failing on some check, not sure how to fix this

**Comment by rhiam** [comment]
> Interesting. It still doesn't show that second file updated. Do you want to find time for us to review on Thursday or Friday? Or @airamare01 can you look at this with Mariam earlier in the day on Thursday or Friday?

Okay, i will look at it with @airamare01  on Thursday when it's convenient for him

**Comment by rhiam** [comment]
@airamare01, this is the commit for the readme file. i did this first actually

**Pull request closed without merging**
