### PR TITLE
Update maternity leave post with keyword

### PR DESCRIPTION
**Pull request by nickmyyz**
@vanesa These are the updates I'm planning! A few hundred people are searching "welcome back from maternity leave" every month, so if we add that keyword throughout the post, more people might see it!

@rebeccadee first of the optimized posts is ready for your review!

### CODE REVIEW

**Review by rebeccadee — COMMENTED** [review]
@nickmyyz LGTM, just added one suggestion to make the case consistent with how we do things now. @vanesa do you want an opportunity to review Nick's changes before we merge?

**Comment by nickmyyz** [comment]
> One other thought I just had, @nickmyyz – maybe as part of this process you could add some "More posts like this" to the end of these posts, since you're already editing them?

Ooh, that's a good idea! I'll add that to this and to the other posts going forward.

**Comment by rebeccadee** [comment]
@nickmyyz @vanesa I'm going to merge this – the changes aren't substantial and I don't want to delay this longer. We can always make tweaks in a further PR 😃

**Comment by rebeccadee** [comment]
@nickmyyz Been going through blog post-related issues in GitHub and came across this! When you have a moment could you add the related posts section? You should be able to merge this yourself but let me know if you are being asked for an approval first. Thanks!

**Comment by nickmyyz** [comment]
@rebeccadee changes made! Two things: It looks like it does require a review and there are conflicting files. I'm not sure what do do about the latter, do you know what to do?

**Comment by rebeccadee** [comment]
Paging @bretthayes – hoping this is quick to review/resolve. This (admittedly old) PR is just to update a blog post but we're getting conflicts on a .json file which is not my area of expertise 😅 Any ideas? 🙏

**Comment by bretthayes** [comment]
No worries @rebeccadee! 😁  The PR just needed to be updated with the main branch since it fell a bit behind. LGTM! The merge conflict is fixed so you should be good to go! 🚀

**Pull request merged**
