### PR TITLE
Blog post for the breaking change to the Go extension

### PR DESCRIPTION
**Pull request by ryan-blunden**

### CODE REVIEW

**Comment by chrismwendt** [comment]
I have yet to implement the change (PR pending https://github.com/sourcegraph/go-langserver/pull/373, still need to address feedback). I'll update this PR once it's merged and I know the docker image hash.

**Comment by ryan-blunden** [comment]
@chrismwendt Is this still happening?

**Comment by chrismwendt** [comment]
Not for 3.6, blocked on https://github.com/sourcegraph/lsp-client/issues/41

**Comment by sqs** [comment]
@chrismwendt Can this be closed?

**Comment by chrismwendt** [comment]
Closing because we no longer plan to make this breaking change to the Go extension.

**Pull request closed without merging**
