### PR TITLE
observability: add guide on how to find alerts

### PR DESCRIPTION
**Pull request by bobheadxi**
Alert channels, bug report page, and Grafana

### CODE REVIEW

**Review by jeanduplessis — APPROVED** [review]

**Comment by jeanduplessis** [comment]
Thanks so much for adding this info @bobheadxi

**Review by unknwon — APPROVED** [review]

**Review by ElizabethStirling — APPROVED** [review]
Looks great, thanks so much!

**Review by daxmc99 — COMMENTED** [review]
🙌

**Pull request merged**
