### PR TITLE
Add back 'Request a demo' CTAs

### PR DESCRIPTION
**Pull request by bretthayes**
This closes sourcegraph/sourcegraph#43956 adding back the "Request a demo" CTA buttons in our `CtaSection` component and in the homepage hero.

I've also ended the [A/B test](https://optimize.google.com/optimize/home/#/accounts/4705180113/containers/15523203/experiments/7/report) for the `Use Sourcegraph` vs. `Search code` CTA button in the global top nav. The `Search code` ended up producing the best results at 54% compared to `Use Sourcegraph` at 46%.

### Other changelog items
- updated codenotify for growth marketing
- removed plausible util and plausible event logging in lieu of relying on Amplitude and eventLogger as the source of truth for events

### Test
Ensure that our `Request a demo` buttons go to `/demo`

### CODE REVIEW

**Comment by bretthayes** [comment]
@kelsey-brown for event logging on About, we send a [bunch](https://github.com/sourcegraph/about/blob/main/src/hooks/eventLogger.ts#L41-L46) of other event properties along with the event name that we can use for filtering in Amplitude. For these, we could check if `textContent` equals `Request a demo` in this case.

I think it would be a good idea to set up some charts for the different types of [CTAs](https://docs.google.com/document/d/1Q1JMzyRmwNKk65KxxtT9EOnxoSf2dHEGkUAPbJkKzI4/edit) we have. This [tracking object map](https://github.com/sourcegraph/about/blob/main/src/data/tracking.ts) is our source of truth that we can use to map to values coming into Amplitude. Hope that helps! 🤓

**Review by st0nebraker — APPROVED** [review]

**Comment by bretthayes** [comment]
@kelsey-brown this is ready for measuring now

**Comment by kelsey-brown** [comment]
For sure, I have this [set up](https://analytics.amplitude.com/sourcegraph/chart/bioy9q9) for some `textContext` filters (`textContext` = `Search code` and `textContext` = `Get free trial`) I just added `Request a demo`- great call out. Button location will definitely come in handy too. Thank you!

**Comment by bretthayes** [comment]
Awesome! This is fantastic! Thanks @kelsey-brown! This will be great to look at for #5910 📈

**Pull request merged**
