### PR TITLE
Support README guide draft

### PR DESCRIPTION
**Pull request by virginiaulrich**

### CODE REVIEW

**Review by airamare01 — APPROVED** [review]
Looks great!

**Review by adeola-ak — APPROVED** [review]
fun :)

**Review by abeatrix — APPROVED** [review]
hypedddd

**Comment by northyg** [comment]
Wow! Such a thorough list. Now we'll know each other's secrets ;)

**Review by northyg — APPROVED** [review]

**Review by DaedalusG — APPROVED** [review]

**Review by adeola-ak — COMMENTED** [review]
just realized current personal project is written twice tho

**Comment by abeatrix** [comment]
> Wow! Such a thorough list. Now we'll know each other's secrets ;)

Now we can reset password for each other  😏

**Comment by virginiaulrich** [comment]
Thanks for catching that @adeola-ak!

**Pull request merged**
