### PR TITLE
remove cloud-beta, redirect to home, copy updates to get-started

### LINKED ISSUE #5264: Remove and redirect /cloud-beta page
We are pausing the Cloud SaaS for Teams on Sourcegraph.com launch and need to update two pages and then take down the cloud-beta page.

**Context**
We believe that pausing work on Cloud SaaS for teams on Sourcegraph.com is necessary to focus on building for our target market for FY23 and beyond (Strategic, Enterprise, Commercial Growth). The support and security risks of adding more teams to Cloud SaaS outweighs the benefit of the limited trial environment it provides.  We need to be laser-focused on enabling Sourcegraph managed trial and production deployment and administration for enterprises.

**Includes**
1)Update copy on [/get-started](https://about.sourcegraph.com/get-started/) and /[get-started/cloud](https://about.sourcegraph.com/get-started/cloud) [see screenshot attached] 
CleanShot 2022-04-19 at 14 16 59@2x

After completing item 1:
2)Take down the /cloud-beta page and redirect the URL to our About homepage temporarily.

Asana: https://app.asana.com/0/1200095757619647/1202142467535925/f

### PR DESCRIPTION
**Pull request by zlonko**
This closes #5264. Here, we:
- Remove the /cloud-beta page!
- Redirect /cloud-beta visits to the home page
- Remove copy regarding _"small teams (Beta)"_ and _"team's repositories"_ on /get-started and get-started/cloud

### Testing
- Please verify the copy updates on /get-started and /get-started/cloud
- Using the Netlify link, please test that you are redirected to home when visiting /cloud-beta
- Test that the static build works

I am new to using Netlify for redirects, so please check my work here! ☀️🔍🔥🐜🔥

### CODE REVIEW

**Comment by zlonko** [comment]
Conferred with @katjuell and will move this to stakeholder review! 

@elzannewentzel: Here is the [link to the project in Ruttl](https://app.ruttl.com/share/ZnwU52ZNMHoZ4FbJiJZS). There are two pages to review, one for `/get-started` and another for `/get-started/cloud`. Because Ruttl doesn't support linked behavior at this time, perhaps we can offer the Netlify link for stakeholders to test the redirect at `/cloud-beta`?

**Comment by st0nebraker** [comment]
> Conferred with @katjuell and will move this to stakeholder review!
> 
> @elzannewentzel: Here is the [link to the project in Ruttl](https://app.ruttl.com/share/ZnwU52ZNMHoZ4FbJiJZS). There are two pages to review, one for `/get-started` and another for `/get-started/cloud`. Because Ruttl doesn't support linked behavior at this time, perhaps we can offer the [Netlify link](https://deploy-preview-5288--sourcegraph.netlify.app/) for stakeholders to test the redirect at `/cloud-beta`?

It looks like if you make a ruttl project as a `Web App` instead of a `Website` type the links and buttons will work. The `Web App` type on ruttl says trial though, so we may not have this capability long term.. I also noticed the carousel buttons don't work, just links with the `Web App`. Slight improvement to view behavior outside of a static HTML page. Not view the ruttle page in preview mode to make things clickable.

You can view a `Web App` project I made [here](https://app.ruttl.com/project/HgnvviGzxsILQnBjC3NM/XHP2j64gP34dDCQ6GULy/tzfDLNc9Kk6JHyFDbKsI/comment) for reference. Maybe another thing to iron out with CE, @elzannewentzel ? CC: @zlonko @bretthayes 

image

**Comment by zlonko** [comment]
Documenting that we have approval from our stakeholders via our new process in Ruttl.

@katjuell Would you mind giving this a final look?

Responding to @st0nebraker: Thank you for these notes on the difference between the `Website` and `Web App` functions. Discrepancies like these add up! It is important to think of our long-term documentation here. Perhaps we can ask Rishab about the Ruttl's roadmap for these features and plan accordingly.

**Review by katjuell — APPROVED** [review]
lgtm!

**Comment by elzannewentzel** [comment]
@zlonko Approved for deployment :) Thank you!

**Pull request merged**
