### PR TITLE
Initial streamline of CE onboarding doc

### PR DESCRIPTION
**Pull request by justdueck**
Changed formatting/layout of CE onboarding to be easier to read through and understand

### CODE REVIEW

**Comment by justdueck** [comment]
I created the initial checklist format and overall streamline of the doc. I included links to as many resources and references I could think of.

TODO asks for Nick & Josh:
- Add any more relevant links/resources
- Add/remove any relevant checklist steps or components
- Double check formatting, spelling and grammar
- Ensure all relevant CE onboarding info is encapsulated

**Comment by mcmillennick** [comment]
@justdueck One thing we might want to do is add the best point of contact for getting access to each of the tools. That way they don't have to go hunting them down. What do you think?

**Comment by justdueck** [comment]
@mcmillennick that's a good idea in theory, however that quickly becomes unscalable. The process being built out is to ask in one central location (internal tools channel) and from their the relevant people can provide access

**Comment by justdueck** [comment]
Also, per @juliasourceress 's rec today, going to merge this PR and will encourage you all to create new PRs for relevant changes on this doc

**Pull request merged**
