### PR TITLE
Security scanners infographic

### LINKED ISSUE #5486: Security scanners infographic
Stakeholders: Fabiana 
What? Host the infographic on the marketing platform.
Why? We will use this infographic on paid campaigns. The pdf has a CTA that invites people to the [Less is more gated page](https://about.sourcegraph.com/guides/fixing-vulnerabilities-less-is-more) page.

[🔗Meta](https://docs.google.com/spreadsheets/d/1xyDzZF7qUuQk2hbCH7D6xuHdtdlHFGOdMZhpSpodcLo/edit#gid=1572625403)
PDF: [Three problems with security scanners.pdf](https://github.com/sourcegraph/about/files/8918105/Three.problems.with.security.scanners.pdf)

Asana: https://app.asana.com/0/1200095757619647/1202409356170656/f

### PR DESCRIPTION
**Pull request by st0nebraker**
Closes #5486 

### Changelog
- Hosts new infographic pdf

### Test
1. Ensure prettier has standardized the proposed changes.
2. Nav to `/guides/three-problems-with-security-scanners.pdf` and ensure pdf loads as expected (CTA at bottom links to `/guides/fixing-vulnerabilities-less-is-more`)

### CODE REVIEW

**Review by zlonko — APPROVED** [review]
You are gtg! I was able to visit the PDF and follow the CTA back to the guide. I noticed there is meta specified in the issue, however, I don't think we can add it considering it is a hosted a PDF and not a proper page.

**Review by bretthayes — CHANGES_REQUESTED** [review]
Looks good and the CTA in the PDF works and links to the less is more page.

As an improvement since this isn't a page, we can name the PDF with a title from the meta so it shows up in the tab.

```sh
brew install exiftool

exiftool -Title="The Three problems with security scanners" filename.pdf
```

Screen Shot 2022-06-22 at 11 02 17 AM

**Comment by st0nebraker** [comment]
> Looks good and the CTA in the PDF works and links to the less is more page.
> 
> As an improvement since this isn't a page, we can name the PDF with a title from the meta so it shows up in the tab.

Interesting, that'd be a great enhancement to our other hosted pdfs too. I can't get the command to run with this error. Any insight to why? This tool is new to me & Dr. Google isn't helping at the moment. @bretthayes 
image

**Comment by bretthayes** [comment]
@st0nebraker it looks like there is a new line returned before the ending double quote for your title string. Also make sure the path to the file is correct. Let me know if that fixes it!

175078885-6c776bc6-eeaa-4bca-a860-ae2c37c601fc

**Pull request merged**
