### PR TITLE
Update values

### PR DESCRIPTION
**Pull request by mercadon**
Replace "be a good human" with "be welcoming and inclusive"

### CODE REVIEW

**Review by virginiaulrich — APPROVED** [review]

**Comment by virginiaulrich** [comment]
Approved, though do wonder if it should be "be welcoming and inclusive ..." Not sure which is easier to read, so that doesn't change my review, but will comment in case anyone else has a stronger sense of which reads better

**Review by dadlerj — APPROVED** [review]

**Comment by dadlerj** [comment]
Thanks for the thoughtful wording and structure here!

**Review by nicksnyder — APPROVED** [review]
Love it, and I think we can/should link directly to this from our job descriptions.

**Review by sqs — APPROVED** [review]

**Comment by mercadon** [comment]
All credit goes to @virginiaulrich on the thoughtful update and rewording of this value! 🥇

**Review by jeanduplessis — APPROVED** [review]
Really happy to see this update ❤️

**Review by christinaforney — APPROVED** [review]

**Pull request merged**
