### PR TITLE
Added gatsby plugin for sitemap

### PR DESCRIPTION
**Pull request by aileenrose**
To improve SEO

### CODE REVIEW

**Comment by ryan-blunden** [comment]
The link in the [`/sitemap.xml`](https://deploy-preview-426--sourcegraph.netlify.com/sitemap.xml) file is returning a 404.

**Comment by aileenrose** [comment]
> The link in the [`/sitemap.xml`](https://deploy-preview-426--sourcegraph.netlify.com/sitemap.xml) file is returning a 404.

I see the sitemap at https://deploy-preview-426--sourcegraph.netlify.com/sitemap.xml

**Comment by ryan-blunden** [comment]
> I see the sitemap at https://deploy-preview-426--sourcegraph.netlify.com/sitemap.xml

Yes, but the [page it links to](https://about.sourcegraph.com/sitemap-pages.xml) is returning a 404.

**Comment by aileenrose** [comment]
> > I see the sitemap at https://deploy-preview-426--sourcegraph.netlify.com/sitemap.xml
> 
> Yes, but the [page it links to](https://about.sourcegraph.com/sitemap-pages.xml) is returning a 404. Sorry if this was not clear in my previous message.

Right since it's going to the TLD where it will soon exist.  :)    
https://deploy-preview-426--sourcegraph.netlify.com/sitemap-pages.xml

**Pull request merged**
