### PR TITLE
Moving hyphens to HTML lists

### PR DESCRIPTION
**Pull request by emchap**
Sorry, this took forever—gave up on trying to do this with a campaign. Can you confirm I didn't screw up any formatting that I didn't catch?

### CODE REVIEW

**Comment by felixfbecker** [comment]
You're a hero! 🦸🏻‍♀️

**Comment by felixfbecker** [comment]
I did notice some unbalanced tags, and realized this would be a lot easier to read and edit by going all-in on HTML for the tables. I just pushed a commit with that change, let me know if this looks good to you!

**Comment by emchap** [comment]
@felixfbecker Looks great; I _much_ prefer not handling them as markdown.

**Comment by emchap** [comment]
Thank you!!

**Pull request merged**
