### PR TITLE
Updating Temporary "PM" for Search

### PR DESCRIPTION
**Pull request by CecilyBee**
@mercadon

### CODE REVIEW

**Comment by CecilyBee** [comment]
@nicksnyder Please use latest commit w/ Joel (not María & Alicja) as temporary PM.

**Comment by nicksnyder** [comment]
What is the context for this change?

**Review by lguychard — CHANGES_REQUESTED** [review]
This change is purely hiring-related (who should be involved in interviewing PM candidates for search), but should not be reflected on the search team's handbook page as it could be misleading re:responsibilities on the team.

**Comment by CecilyBee** [comment]
@nicksnyder @lguychard Loïc is correct in that I was looking to change the list for scheduling purposes. I will change the job description instead. Thanks both!

**Pull request closed without merging**
