### PR TITLE
Blog/go modules

### PR DESCRIPTION
**Pull request by r0yce**
- added missing images
- removed notes left in doc
- removed repeated text.
- minor edits

### CODE REVIEW

**Comment by r0yce** [comment]
This PR will help to make the latter part of the article more readable. There were references to images, as examples, where there are none.

**Comment by ryan-blunden** [comment]
@r0yce Please replace the new jpeg with a version that's 740px wide as its 1.52Mb.

**Comment by r0yce** [comment]
@ryan-blunden i've resized the image as requested. apologies for the large image size.

**Comment by ryan-blunden** [comment]
Thanks @r0yce for live-blogging!

**Pull request merged**
