### PR TITLE
Add resources index page

### LINKED ISSUE #5234: Add /guides section
**PAUSED**: Demand gen will provide a new request for this work.

The Demand gen team want to add a /guides section to the About site to give recent gated content assets a permanent home on the marketing site.

Requirements can be found [here](https://docs.google.com/document/d/1O-xMHFhoAqRPf6twGolufkdRbpcb85kBZw-jwhFu6VM/edit)

This is not a blocker to anything, but we do have several more guides slated for publication soon

Asana card: https://app.asana.com/0/1200095757619647/1202058387310661/f

### PR DESCRIPTION
**Pull request by katjuell**
Adds a `resources` index page and closes #5234 

## To Test 
- Visit `/resources` and check that links work and card component looks correct.

### CODE REVIEW

**Comment by katjuell** [comment]
@elzannewentzel @bretthayes I'm marking this as a draft because I still have some questions here: there seems to be a back and forth in the thread about what the location of the page should be (`guides` v `resources`) and the exact content of the header/ subheader. Similarly, it's not clear to me what should be added to the top-level Nav (content from the main doc? The thread in the doc?).

Not sure about next steps?

**Comment by bretthayes** [comment]
@elzannewentzel are we abandoning this index or still waiting on feedback?

**Comment by elzannewentzel** [comment]
It might still be relevant, I'll follow up :)

**Comment by bretthayes** [comment]
@elzannewentzel we could build on this with the upcoming resources/filtering 🤓

**Comment by bretthayes** [comment]
Closing this in lieu of the new resources page - #5669

**Pull request closed without merging**
