### PR TITLE
Incident response use case /non-blocking feedback

### LINKED ISSUE #5287: Non-blocking feedback for Incident Response Use Case Page
Implement the non-blocking feedback for the Incident Response page.
https://docs.google.com/document/d/18dNP6QihejP8CVSm-tdmbH20D5beFYlGXyBme0286U4/edit#

### PR DESCRIPTION
**Pull request by zlonko**
This closes #5287. Here, we implement the remaining feedback from our Marketing stakeholders, re: copy updates, a changed icon, and logo treatment.

The QA doc can be found [here](https://docs.google.com/document/d/18dNP6QihejP8CVSm-tdmbH20D5beFYlGXyBme0286U4/edit#).

### Notes
- Crosshairs icon changed to magnifying glass
- Copy changes in `CustomCarousel`
- Copy changes in blog descriptions
- Reformat "What does it mean for you?" on this and other Use Case pages
- Center and slightly enlarge Cloudflare logo in feature box

### Testing
- Open `use-cases/incident-response`
- Check that the updates marked "Non-Blocking" in the QA doc are accurate
- Test the static build

### CODE REVIEW

**Comment by zlonko** [comment]
@elzannewentzel This is almost ready for Engineering review. Two comments about the "Incident response is stressful and overwhelming" section are unresolved, so I left a follow-up reply in the doc.

**Review by katjuell — APPROVED** [review]
lgtm!

**Comment by zlonko** [comment]
Hi @elzannewentzel: Here is the Ruttl reflecting updates to these non-blocking comments: [link](https://app.ruttl.com/share/WIwXYtm2hBC0sCrvsBHQ)! 

It looks like we are still anticipating sign-off on issue https://github.com/sourcegraph/about/issues/5237. Perhaps we can:
1. Await final approval from Marketing for #5259 (blocking feedback)
2. Afterwards, share this PR's Ruttl with Marketing for review (non-blocking feedback)
3. Upon approval, merge this PR into #5259, then deploy

If we have followed a different process in the past, I'm happy to follow that instead!

**Comment by elzannewentzel** [comment]
@zlonko Thank you, agree with the plan 👍  I've asked Jenny to confirm blocking feedback for https://github.com/sourcegraph/about/pull/5259

**Comment by zlonko** [comment]
@elzannewentzel To keep things moving today, and because we are awaiting feedback on non-blocking feedback here, I went ahead and deployed #5259 with the intent to push this branch into main once it is ready.

**Comment by zlonko** [comment]
Nice! I resolved the conflict. It looks about ready for your final take @bretthayes!

**Review by bretthayes — APPROVED** [review]

**Pull request merged**
