### PR TITLE
Code intel: add team logo, we already sound cool

### PR DESCRIPTION
**Pull request by efritz**
Well if [@slimsag](https://github.com/sourcegraph/about/pull/1560) is doing it...

### CODE REVIEW

**Review by Strum355 — APPROVED** [review]
:brain: :boom: 9/10 needs more catch-name

**Comment by slimsag** [comment]
🤣 looks like the intro to the illuminati videos I watch on YouTube

**Comment by nicksnyder** [comment]
Right justify and text wrap of distribution team is better :)

**Comment by efritz** [comment]
Big talk for a guy with no logo

**Comment by nicksnyder** [comment]
Game on
gears

**Comment by efritz** [comment]
oH nO fRiEnDlY cOmPeTiTiOn

**Review by aidaeology — APPROVED** [review]
LGTM

**Comment by gbrik** [comment]
ship it :triumph:

**Review by garobrik — APPROVED** [review]

**Comment by efritz** [comment]
Shipped

**Pull request merged**
