### PR TITLE
Remove inline style on image to fix scaling on mobile

### PR DESCRIPTION
**Pull request by csbailey5t**
Re: Hashimoto Dev Tool Time iPad workflow image

### CODE REVIEW

**Comment by rebeccadee** [comment]
@csbailey5t Thank you for doing this! There may not be a way around this, but removing the sizing makes the inline images huge now: 

Screenshot 2021-08-31 at 11 48 47

**Comment by csbailey5t** [comment]
We probably need to set a more explicit `max-width`. Right now, our CSS is calculating `max-width` and `max-height` based on viewport width and height. We *should* be fixing this in the underlying CSS so we aren't needing to explicitly set any styles in our markdown, but that's a future step.

**Comment by csbailey5t** [comment]
Checking back over previous posts, this is a bug that affects any of the images in the blog that have the explicitly set smaller height and width.

**Comment by csbailey5t** [comment]
@rebeccadee I'm going to go ahead and merge this, since the images in this post per this PR are consistent with the video embed at the bottom, and slightly large images on a large desktop are probably better than having distorted images on mobile. A real fix for this can be part of the larger blog redesign.

**Comment by rebeccadee** [comment]
High agency in action, thanks @csbailey5t!

**Pull request merged**
