### PR TITLE
Embed demo form to Code-Insights pg

### LINKED ISSUE #5235: Add Request a Demo form on CI landing page
The Marketing team wants to update the [Code Insights landing page](https://about.sourcegraph.com/code-insights) to make it easier for someone to request a demo.

In the current state, there is a "Request a demo" CTA that links to a new page with a form.

New state: 
- A form is embedded directly onto the landing page. The only field would be Work email + the privacy policy notice.
- Example of the form on the [Dev Onboarding page](https://about.sourcegraph.com/accelerate-dev-onboarding/)
- Updated form embed code:

<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
 hbspt.forms.create({
 region: "na1",
 portalId: "2762526",
 formId: "1367e810-da5f-4abd-97bc-49df5a5b459f"
});
</script>
The form should prompt ChiliPiper 🌶️
- Copy for privacy: By submitting, I agree to Sourcegraph's [Terms of Service](https://about.sourcegraph.com/terms) and [Privacy Policy](https://about.sourcegraph.com/privacy).
- Button CTA: Request a demo

Not urgent, but this will hopefully help drive more pipeline.

Asana card: https://app.asana.com/0/1200095757619647/1202053080369706/f

### PR DESCRIPTION
**Pull request by st0nebraker**
Closes #5235 by embedding new HubSpot Request Demo form

### Test
Navigate to `/code-insights` and ensure new form meets requirements

**BEFORE**
image
image

**AFTER**
image
Screen Shot 2022-04-19 at 12 49 03 PM

### CODE REVIEW

**Review by bretthayes — COMMENTED** [review]
This looks good, but is the form also supposed to be in the hero, replacing the request a demo button? Seems like the ticket request mentions implementing the forms similar to the [dev onboarding](https://about.sourcegraph.com/accelerate-dev-onboarding/) page. Might be a good idea to confirm this with @elzannewentzel.

**Comment by st0nebraker** [comment]
> This looks good, but is the form also supposed to be in the hero, replacing the request a demo button? Seems like the ticket request mentions implementing the forms similar to the [dev onboarding](https://about.sourcegraph.com/accelerate-dev-onboarding/) page. Might be a good idea to confirm this with @elzannewentzel.

Hmm, yea it's probably wanted for both "Request demo" button spots on the page. Updated! 👍  @bretthayes

**Review by bretthayes — APPROVED** [review]
Sweet, meets the ticket requirements!

Just need a +1 from @elzannewentzel before merging.

**Comment by elzannewentzel** [comment]
+1 ! :) 

Just noting the error messages here, I don't think we have control over this but the duplication should be fixed.
Screenshot 2022-04-21 at 21 39 02

**Comment by st0nebraker** [comment]
> +1 from me, will send for stakeholder review! :)
> 
> Just noting the error messages here, I don't think we have control over this but the duplication should be fixed. Screenshot 2022-04-21 at 21 39 02

So I think they're technically 2 separate error messages. One triggers if you click past a required field without filling it out, or with improper format. The second error is for the submission button, indicating why the submission is blocked. The phrasing is just pretty generic, and with only one field in the form, it is unclear and a bit bad UX, I agree. We can't change it, yea, HubSpot has the controls.

**Comment by elzannewentzel** [comment]
@st0nebraker Can you have a look at the form duplication in the header, please?
Screenshot 2022-04-22 at 08 38 02

**Comment by elzannewentzel** [comment]
@st0nebraker For the errors, Greg had a look and Hubspot does not seem to have a lot of flexibility around the errors. He suggested trying this to hide one of the errors.
The first one can be hidden by adding something like the below example to the page's style sheet:
.hs_error_rollup {
    display: none;
}"
Can you try this and see if it works? It's probably styling we would need to consider for all these forms.

**Comment by st0nebraker** [comment]
Is this PR approved by QA otherwise @elzannewentzel ? The form error enhancement will take more digging as it can't be styled in our repo, it has to be done on HubSpot itself. I made a [follow-up story](https://github.com/sourcegraph/about/issues/5286) to bring this enhancement in later. It's not technically a bug but an enhancement since this is expected behavior of the form.

**Comment by elzannewentzel** [comment]
@st0nebraker Yes approved otherwise, thank you for checking!

**Comment by bretthayes** [comment]
For context, we can't style or add style overrides to our HubSpot forms directly with CSS in the codebase or any content inside iframe elements that live outside our domain because it's an XSS cross-site-scripting issue. The only way we'll be able to style forms is to modify the global HubSpot stylesheet that lives on HubSpot or use the very limited styling abilities in HubSpot's form builder.

Another option would be to leverage building custom forms/form components and use the HubSpot API, but that has a bigger scope. It would be nice to have prettier forms in the future. ✨ 

cc: @st0nebraker @elzannewentzel

**Pull request merged**
