### PR TITLE
observability docs: move file to where it's referenced

### PR DESCRIPTION
**Pull request by rvantonder**
https://github.com/sourcegraph/about/pull/1221 broke docsite build. It looks like this file should live where I moved it in this PR see https://github.com/sourcegraph/about/runs/1279046251#step:4:23

### CODE REVIEW

**Comment by bobheadxi** [comment]
Oh, I started to try and fix the references in #1783 😅

**Comment by rvantonder** [comment]
@bobheadxi OK, I looked at the docsite logs and it's this file--based on the change, the referenced file should live where I moved it, and this PR unbreaks the build (which is really the part I care about :-) it's either this PR or revert the other). Can I get a stamp here please, and you can fix up anything else that needs Real Fixing (TM) in your PR, if needed?

**Review by bobheadxi — APPROVED** [review]

**Comment by bobheadxi** [comment]
(we might want to make the docsite build a required check too)

**Comment by rvantonder** [comment]
agree!

**Pull request merged**
