### PR TITLE
Add Anyscale logo to Cloud Beta landing page

### LINKED ISSUE #5071: Add Anyscale logo and quote to /cloud-beta
Context
We have one beta customer, Anyscale, who just agreed to let us use a quote from them + their logo. 

Request:
Add the logo + quote at the top right of /cloud-beta 
While we’re at it, make small tweaks to the copy at the top of that page

Resources 
🖇️Customer logo (attached) 
💬 Quote: 
"Sourcegraph makes it so much easier to onboard to large codebases. It's an absolute game changer when it comes to navigating around an ecosystem with hundreds of repositories or even multiple organizations."
🔗[Copy doc for copy edits](https://docs.google.com/document/d/1AtYBFIVPnhiTQF0j8EHkcKvrTkwbCML6Lxj0p0aTCvs/edit) (January 10th version)

### LINKED ISSUE #5093: Design input for Anyscale logo and quote
We are looking for some design input for #5071 

The request is to add a logo and quote to the top of the [cloud beta page](https://about.sourcegraph.com/cloud-beta/), but the requestor didn't have a super specific design in mind. Mate (who will be working on the code changes) called out screen real estate on smaller screen sizes, so looking for your expertise.

You can see more context in the conversation in the [Asana card](https://app.asana.com/0/1200095757619647/1201634832121942/f) (had some activity happen here before fully moving over to Github projects, sorry for the two systems!)

### PR DESCRIPTION
**Pull request by bretthayes**
### What should this PR do?

- Closes #5071 
- Closes #5093 
- Uses SVG logo from Anyscale for better quality – not the png provided in the ticket
- Fixes bug from custom carousel pushing the viewport
- Fixes centre alignment for the unordered list in the waitlist section

## Screenshot Preview
Screen Shot 2022-02-04 at 5 36 05 PM

### CODE REVIEW

**Comment by marybelzer** [comment]
@bretthayes Is there a preview/staging link I can share with stakeholders?

**Comment by bretthayes** [comment]
@marybelzer Yes – if viewing the Conversation Tab, at the bottom of the PR, if you scroll within the list of all the “checks” where it says “All checks have passed”, there is a link if you click on `Details` on the right of the `deploy/netlify` task. If you click on that, you can see the preview environment/site of this code. You'll have to add the URI of `cloud-beta` to get to this page though.

[Here's the preview for convenience](https://deploy-preview-5115--sourcegraph.netlify.app/cloud-beta/)

**Comment by marybelzer** [comment]
@bretthayes Oh thank you good to know! Sharing with stakeholders and will report back/approve as soon as I hear back

**Review by stephzabala — APPROVED** [review]

**Review by katjuell — CHANGES_REQUESTED** [review]
The iframe isn't working on the staging link. Looks like the request is getting canceled. True in Firefox, Chrome, and Safari. Works in local dev, though.

We seem to be using privacy enhanced embeds elsewhere in the site — wonder if that's a factor? The [`YouTube` component](https://sourcegraph.com/github.com/sourcegraph/about/-/blob/website/src/components/YouTube.tsx) defaults to that I notice.

**Comment by bretthayes** [comment]
@katjuell I remember @mgyorffy mentioning that these videos don't load on the staging environment and only in production.

**Comment by bretthayes** [comment]
@marybelzer do we have approval from stakeholders?

**Comment by marybelzer** [comment]
@bretthayes Not yet, I will ping them with a reminder!

**Pull request merged**
