### PR TITLE
new Terms of Service & Privacy Policy

### PR DESCRIPTION
**Pull request by dadlerj**

### CODE REVIEW

**Comment by francisschmaltz** [comment]
Took a quick look and I love the added color splashes!

**Comment by dadlerj** [comment]
This is updated! @sqs this is probably dead last in your stack of priorities right now, and no rush on it, but it's worth you taking a peek at the terms-private.md and terms-dotcom.md files, to see how the wording strikes you before this is merged.

Still to do:

- [ ] Add dates
- [ ] Once merged, email all users about updated terms

**Comment by dadlerj** [comment]
Totally forgot about this PR, @sqs let me know if you'd like to review!

**Comment by dadlerj** [comment]
@francisschmaltz let me know if this works for you

**Pull request merged**
