### PR TITLE
Reorder sections on Code Insights

### LINKED ISSUE #5408: Update Code Insights Landing Page
Based on heatmapping data for the recent[ Code Insights page](https://about.sourcegraph.com/code-insights), we are seeing that viewers aren't interacting with the "How engineering teams use Code Insights" module. We would like to reorder the page as follows:

1. Hero: Track what really matters to you and your team.
2. Finally, useful engineering metrics you define (animation)
3. Trusted by engineering teams worldwide (quote)
4. Engineering leadership with superpowers
5. How engineering teams use Code Insights
6. See Code Insights in action
7. Popular Code Insights templates
8. Get started with Code Insights
9. Learn more

[Figma](https://www.figma.com/file/o1QRtdQI0ozKq0n7ATrKlx/Brand-DLS?node-id=7341%3A49748)
Use Figma as an example of the reorder of content on the page. Do not implement any template or styling changes.

Asana: https://app.asana.com/0/1200095757619647/1202354409559878/f

### PR DESCRIPTION
**Pull request by zlonko**
This closes #5408. It reorders the sections on the Code Insights page according to heatmapping feedback.

### Changelog
- Reorganized the Code Insights page
- Flipped the video and text on "Finally..." section to match the reading order
- Fixed the tab style to match our universal pattern
- Edited the headline height for the `CustomCarousel` on mobile
  - Extra space that appeared below the headline made it difficult to view an entire slide on mobile

### Notes
- This issue asks that we only update the order of the existing components at this time
- The correct order can be referenced in this [Figma](https://www.figma.com/file/o1QRtdQI0ozKq0n7ATrKlx/Brand-DLS?node-id=4422%3A86874) file

### Test
1. Ensure prettier has standardized the proposed changes.
2. Please navigate to `/code-insights`
3. The order should read:
  - Hero: Track what really matters to you and your team.
  - Finally, useful engineering metrics you define (animation)
  - Trusted by engineering teams worldwide (quote)
  - Engineering leadership with superpowers
  - How engineering teams use Code Insights
  - See Code Insights in action
  - Popular Code Insights templates
  - Get started with Code Insights
  - Learn more

### CODE REVIEW

**Review by st0nebraker — APPROVED** [review]
Looks good! 🌟  Thanks for the small CSS cleanup too

**Review by bretthayes — APPROVED** [review]
Looks good to me! The only thing I noticed was that the CI graphs are reactive and not responsive but I think that's a known issue and out of scope for this ticket. Something we should maybe keep in mind for a future improvement.

**Comment by zlonko** [comment]
Thanks, everyone! @elzannewentzel The [staging link](https://deploy-preview-5444--sourcegraph.netlify.app/code-insights) is ready for our stakeholders!

**Comment by zlonko** [comment]
@bretthayes I saw this as well. Looking again, I noticed we could also improve the responsiveness of the code samples. Here is an issue to track these improvements: https://github.com/sourcegraph/about/issues/5451.

@elzannewentzel The [staging link](https://deploy-preview-5444--sourcegraph.netlify.app/code-insights) is ready for our stakeholders!

**Comment by zlonko** [comment]
Shipping this with a note to revisit the placement of the ChiliPiper form pending information on which CTA is clicked most (Joel).

**Pull request merged**
