### PR TITLE
Adding assigned CSE

### PR DESCRIPTION
**Pull request by virginiaulrich**

### CODE REVIEW

**Comment by virginiaulrich** [comment]
@christinelovett @justdueck @mike-r-mclaughlin @amenne @abeatrix @gabtorre @DaedalusG @hicksca @airamare01 @amberfurbush0317 @alexAtSourcegraph @benjaminwgordon -- review if you have time, but you technically already have so this more just FYI :) .. a Slack post is next!

**Review by alexAtSourcegraph — APPROVED** [review]
Nice!

**Review by christinelovett — COMMENTED** [review]
LGTM :-)

**Comment by airamare01** [comment]
Reviewed!

**Review by abeatrix — COMMENTED** [review]
Lgtm

**Review by benjaminwgordon — COMMENTED** [review]
LGTM

**Pull request merged**
