### PR TITLE
Update internet and mobile phone info

### PR DESCRIPTION
**Pull request by quinnkeast**
With our remote teammates, the reimbursement for internet and mobile phone reflects actual expenses rather than a fixed amount. As I reference this page from time to time to make sure I'm not forgetting anything while creating monthly invoices, I updated the details to reflect this. In addition, medical benefits are for US-based full-time employees.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Does it? I always put the allowance on my invoice (in accordance to the handbook).

**Comment by quinnkeast** [comment]
> > With our remote teammates, the reimbursement for internet and mobile phone reflects actual expenses rather than a fixed amount.
> 
> Does it? I always put the allowance on my invoice (in accordance to the handbook).

The [guidelines for non-US teammates](https://about.sourcegraph.com/handbook/people-ops/invoices) changed in August or so, and now instead of an set monthly amount, we submit receipts for each expense and include a line item for the actual expense amount.

**Comment by chayim** [comment]
> The [guidelines for non-US teammates](https://about.sourcegraph.com/handbook/people-ops/invoices) changed in August or so, and now instead of a set monthly amount, we submit receipts for each expense and include a line item for the actual expense amount.

These are for non-fringe benefits expenses. Mobile, internet, and wellness are fixed benefit amounts (as told to my by @mercadon).

**Comment by quinnkeast** [comment]
Interesting! In that case, @mercadon can you confirm? Then I'll change this PR to update the [Submitting an invoice (teammates based outside of US)](https://about.sourcegraph.com/handbook/people-ops/invoices) page instead.

**Comment by felixfbecker** [comment]
@quinnkeast it says so in the page you linked:

> - Include any **expenses** incurred that month as **individual line items** and attach all **expense receipts** to the same email with the invoice.
> - Include any **fringe benefits** on your invoice as **individual line items** as well (cell phone, internet, wellness benefits, etc.).

So add as line items, but no receipts with exact amounts needed for fringe benefits.

**Comment by mercadon** [comment]
> Interesting! In that case, @mercadon can you confirm? Then I'll change this PR to update the [Submitting an invoice (teammates based outside of US)](https://about.sourcegraph.com/handbook/people-ops/invoices) page instead.

Confirming! Only fringe benefits require receipts, but mobile, internet, and wellness are fixed amounts :)

**Pull request closed without merging**
