### PR TITLE
Add idea becomes a machine liveblog & ecuincla babosa liveblog

### PR DESCRIPTION
**Pull request by RSid**

### CODE REVIEW

**Comment by ryan-blunden** [comment]
Looking good @RSid!

**Comment by ryan-blunden** [comment]
@RSid Your title still contains "First pass" so i won't merge this yet, but let me know once it's ready.

**Comment by RSid** [comment]
@ryan-blunden oops, sorry about that! Ready when you are, name changed.

**Comment by RSid** [comment]
Oop, forgot that adding the Escuincla liveblog would just throw it in the same PR instead of allowing me to make another - let me know if I should revert & wait to put up that PR until this one is merged, or whether it's ok for the 2 blogs to go together.

Thanks!

**Comment by ryan-blunden** [comment]
This is awesome work @RSid. Thanks for liveblogging!

**Pull request merged**
