### PR TITLE
Updates customer logos section/carousel

### LINKED ISSUE #5173: Add MercadoLibre logo
Add MercadoLibre logo to our carousel. 

Location: Where the Apex logo is. We can move the Apex logo to the back of the carousel of have it next to MercadoLibre. Whatever is easier. 
mercadolibre

### PR DESCRIPTION
**Pull request by bretthayes**
Closes #5173 by adding the Mercado Libre logo in the location of the Apex logo and moving the Apex logo to the end of the carousel

### CODE REVIEW

**Review by katjuell — COMMENTED** [review]
LGTM! Are you doing Unity in this PR as well? I saw an open [question](https://github.com/sourcegraph/about/issues/5170#issuecomment-1057523271) from you about it on the ticket.

**Review by marybelzer — APPROVED** [review]
MercadoLibre looks good, should have an answer on the Unity logo shortly!

**Comment by bretthayes** [comment]
@marybelzer do we have an update on the unity logo?

**Review by katjuell — APPROVED** [review]
lgtm!

**Pull request merged**
