### PR TITLE
distribution: Update goals with 3.21 status

### PR DESCRIPTION
**Pull request by pecigonzalo**

### CODE REVIEW

**Comment by bobheadxi** [comment]
^ the codenotify didn't seem to work for the team tag @nicksnyder

**Comment by pecigonzalo** [comment]
Could it be because I added Nick by hand before it ran?

**Comment by nicksnyder** [comment]
It is probably because the default token that is available to GitHub actions doesn't have permission to read members of an org, which prevents team mentions from working. I am updating the token here to hopefully fix this: https://github.com/sourcegraph/sourcegraph/pull/14051

**Comment by nicksnyder** [comment]
darn, still didn't work, I am going to change a few permissions and push some empty commits to see if I can quickly fix this, sorry for spam!

**Comment by nicksnyder** [comment]
Oops, updated token in the wrong repo. Going to try again now that token is updated here: 3a45eb95727b6d9acf2794a83ac9bc5aa0797fc8

:)

**Comment by nicksnyder** [comment]
^ CODENOTIFY is fixed

**Comment by pecigonzalo** [comment]
@nicksnyder could you review?

**Review by uwedeportivo — APPROVED** [review]

**Review by ggilmore — APPROVED** [review]
LGTM (the Dhall stuff is accurate, and the timeline for the other goals makes sense from my understanding)

**Pull request merged**
