### PR TITLE
3.5.md RITZA edit II

### PR DESCRIPTION
**Pull request by worktheclock**
To end line 208.

### Test

1. Ensure prettier has standardized the proposed changes.

### CODE REVIEW

**Comment by sqs** [comment]
@jdorfman What's the status of this PR?

**Comment by jdorfman** [comment]
@sixhobbits is this good to merge?

**Comment by sixhobbits** [comment]
@jdorfman - good from our side but looks like it was deleted? https://about.sourcegraph.com/podcast/jean-yang

**Comment by jdorfman** [comment]
@sixhobbits I'm digging into what is going on. Jean's episode [is live](https://open.spotify.com/episode/2Q6cSQpqKqfQDhQVADhur7) but not sure  why I created https://github.com/sourcegraph/about/commit/e0fff3e2f66a869b80e68546064f8b7d0ab9f7e9

In the meantime, can you create a new PR that will get this episode live again with your fixes?

**Comment by sixhobbits** [comment]
@jdorfman sure here we go https://github.com/sourcegraph/about/pull/5981

**Comment by jdorfman** [comment]
Thanks. Can you send an empty commit to restart the tests?

I read the Slack thread but it still didn't give context from what I read.

**Comment by sixhobbits** [comment]
I sent the empty commit to https://github.com/sourcegraph/about/pull/5981 - is that what you meant? This one can probably be closed.

**Comment by jdorfman** [comment]
@sixhobbits weird, I will need to dig in when I get back.

**Review by jdorfman — APPROVED** [review]

**Comment by jdorfman** [comment]
Closing see b95335c

**Pull request closed without merging**
