### PR TITLE
Add livestream video to 4.0 landing

### PR DESCRIPTION
**Pull request by bretthayes**
Follow up for #5690, adding the livestream video. 

### Changelog
- added livestream video to the bottom of the page using the TwitchPlayer
- removed Bootstrap classes for YouTube video aspect ratios in lieu of Tailwinds video aspect ratio utility class

### Test

1. Ensure prettier has standardized the proposed changes.
2. Ensure livestream video plays

### CODE REVIEW

**Review by st0nebraker — CHANGES_REQUESTED** [review]
One thing I noticed for mobile (I know there wasn't a spec for mobile), maybe the titles should left-align at small breakpoints and below? Since that's our pattern on most pages. Other aspects of the same page do this already, like the `Top updates released in Sourcegraph 4.0` section. What do you think?
image

**Comment by traceyljohnson** [comment]
@st0nebraker Something to double check is that the H1 and H2's go down to their respective mobile sizes (6xl and 4xl). That will help it to not break so oddly (unless they already are those sizes and I'm just mistaken).

**Comment by st0nebraker** [comment]
> @st0nebraker Something to double check is that the H1 and H2's go down to their respective mobile sizes (6xl and 4xl). That will help it to not break so oddly (unless they already are those sizes and I'm just mistaken).

Looks like they are the right size, just sits a bit odd at that 320px XS screen width

**Review by fabicastp — APPROVED** [review]

**Review by st0nebraker — APPROVED** [review]
LGTM! Tested the Youtube component on a few other pages & looks groovy 😎

**Comment by bretthayes** [comment]
Awesome! Thanks Beckz and Fabz! 🎉

**Pull request merged**
