### PR TITLE
Reflecting decision to default Zendesk to private notes

### PR DESCRIPTION
**Pull request by virginiaulrich**
Updates to reflect our team decision ([here](https://sourcegraph.slack.com/archives/C01JR51JR5J/p1615592245133500)) to default Zendesk replies to internal/private notes (instead of public) since much of our work happens in internal notes. 

Pretty sure that you will NOT see Zendesk work like this until you have a new ticket (even though the setting has been changed, I don't think Zendesk applies to to any ticket created before 1:30pm pacific on 2021-03-15).

Having the team review for awareness of the change, plus how it works ^, and to suggest any changes to make the updates more clear!

### CODE REVIEW

**Review by northyg — APPROVED** [review]
Looks good to me!

**Review by abeatrix — APPROVED** [review]
Noted!

**Review by DaedalusG — APPROVED** [review]
Looks good!

**Comment by virginiaulrich** [comment]
@airamare01 @adeola-ak I am going to go ahead and merge these changes now, let me know if you have any questions!

**Comment by adeola-ak** [comment]
got it! looks good

**Pull request merged**
