### PR TITLE
Update support-bios.md

### PR DESCRIPTION
**Pull request by rhiam**

### CODE REVIEW

**Comment by rhiam** [comment]
@airamare01 this is the update i did

**Comment by airamare01** [comment]
Hey @rhiam. I can see the link to your readme in the support bios page but the readme file itself is missing from this commit.

Could you please add it or better yet you can delete this branch and make the commit in a fresh branch where:
1. You have the readme markdown file in support bios
2. The link to the file in the page.

**Comment by rhiam** [comment]
> Hey @rhiam. I can see the link to your readme in the support bios page but the readme file itself is missing from this commit.
> 
> Could you please add it or better yet you can delete this branch and make the commit in a fresh branch where:
> 
> 1. You have the readme markdown file in support bios
> 2. The link to the file in the page.

Do you mean the commit has to contain that of the readme file and this ?

**Comment by airamare01** [comment]
Yes that's correct

**Pull request closed without merging**
