### PR TITLE
Update pricing page

### PR DESCRIPTION
**Pull request by francisschmaltz**
@dadlerj Updated pricing page. Thoughts?

screen shot 2018-12-07 at 11 18 08 am
screen shot 2018-12-07 at 11 18 35 am
screen shot 2018-12-07 at 11 18 52 am

### CODE REVIEW

**Comment by francisschmaltz** [comment]
> Could you also add "Limited starter package available" to the bottom of the Enterprise column, with a link to the contact form page if you click it?

We already have a free trial button that takes the user to the contact page. We could add copy on there if you wanted.

> Looks like we could make these wider and potentially get "registry" onto the first line :)

I wanted to but it looks odd at a wider frame.

**Comment by dadlerj** [comment]
> We already have a free trial button that takes the user to the contact page. We could add copy on there if you wanted.

Is your reticence to add it because that would cause the number of lines on the two cards to look imbalanced? I'm debating whether to remove one of the other lines if so (or if there's some other way to get "registry" onto a single line :) )

**Comment by sqs** [comment]
- "HA cluster support" - Customers don't care about HA nearly as much as they do about high scalability. I know this is on there now, but we should change it. It should be "High-scale cluster support (Kubernetes)"
- "SSO Support" - "S" in "Support" should be lowercase
- The "for 200 users" is small. I missed it initially even when I was looking for it.

**Comment by francisschmaltz** [comment]
> Is your reticence to add it because that would cause the number of lines on the two cards to look imbalanced?

The lines can always be balanced with more added. I thought you meant adding a link elsewhere, which I thought was redundant. If it's just a block of text then I'm okay with it – it just wouldn't be a link.

> The "for 200 users" is small. I missed it initially even when I was looking for it.

On the site it's still visible enough for someone looking for information for the first time.

**Comment by dadlerj** [comment]
>The lines can always be balanced with more added. I thought you meant adding a link elsewhere, which I thought was redundant. If it's just a block of text then I'm okay with it – it just wouldn't be a link.

Ah, nope! I just wanted to add an extra line to the features list with that text. LMK if that sounds doable.

**Comment by francisschmaltz** [comment]
@dadlerj are you okay having the limited start pack in the sosumi copy below? 
screen shot 2018-12-07 at 11 21 37 am

**Comment by francisschmaltz** [comment]
Mobile screenshots. Changed button to block buttons on mobile.
screen shot 2018-12-07 at 11 53 34 am
screen shot 2018-12-07 at 11 53 40 am
screen shot 2018-12-07 at 11 53 51 am

**Pull request closed without merging**
