### PR TITLE
Add draft blog post about improving language support in 2019

### PR DESCRIPTION
**Pull request by chrismwendt**
This could probably use a lot of wordsmithing, @sqs.

Does this accurately convey our intention and plan for 2019? Will it grab the attention of prospective developers who can help out?

### CODE REVIEW

**Comment by sqs** [comment]
Your gdoc had a lot of other good content. Some of it was fairly internal, but not sensitive info. Why not include it? It may be of interest to other people working on language servers.

**Comment by chrismwendt** [comment]
:+1: I added back most of the content from the Background section of the gdoc.

**Comment by chrismwendt** [comment]
I added a section for Python and Swift.

Anything other changes before I post this?

**Comment by chrismwendt** [comment]
@sqs Does this look ready to post?

**Comment by chrismwendt** [comment]
@ryan-blunden Can a copy editor make changes on this PR? Or I can merge this into master and they can make a separate PR with changes.

**Comment by ryan-blunden** [comment]
This is really good! Let's merge into master and a copy editor can perform any edits and submit a new PR.

**Pull request merged**
