### PR TITLE
Add Figma for Sourcegraphers link

### PR DESCRIPTION
**Pull request by rrhyne**

### CODE REVIEW

**Review by AlicjaSuska — APPROVED** [review]
Awesome @rrhyne great work!

**Comment by rrhyne** [comment]
I was running late on time and let out measuring! :|

**Comment by AlicjaSuska** [comment]
We can also add this article as a resource: https://www.smashingmagazine.com/2020/09/figma-developers-guide/

**Comment by rrhyne** [comment]
Good call, please do so!

**Comment by AlicjaSuska** [comment]
@rrhyne maybe we should add it also to the engineering onboarding?

**Comment by rrhyne** [comment]
I have a pull request to add the video in that document already.

**Review by christinaforney — APPROVED** [review]

**Pull request merged**
