### PR TITLE
Use Case: Code Reuse thumbnail & copy changes

### PR DESCRIPTION
**Pull request by st0nebraker**
Implements feedback for #5239
- Copy updates to Code Reuse use-case.
- Thumbnail update to resource linked

### CODE REVIEW

**Comment by zlonko** [comment]
@st0nebraker Is there a doc I can reference for checking the updated copy?

**Review by bretthayes — COMMENTED** [review]
+1 what @zlonko said. Is there a ticket for this and a doc with the changes requested?

**Comment by st0nebraker** [comment]
@bretthayes @zlonko Updated description with the ticket. This feedback came after approval for this page. Note, some of the feedback was given via Slack.

**Review by zlonko — APPROVED** [review]
All of the copy aligns with the doc, and the four links work as expected. This looks good to me!

**Pull request merged**
