### PR TITLE
Add on-demand videos to event page

### PR DESCRIPTION
**Pull request by aileenrose**
Screen Shot 2020-06-01 at 8 37 08 PM

### CODE REVIEW

**Comment by aileenrose** [comment]
> WDYT about having two sections – 1 for upcoming and 1 for videos
I thought about that, but for this month, there is just one which seems unbalanced.  I could rework the layout of the single meetup to cover the full width.    This is just a quick fix.

**Comment by aileenrose** [comment]
I reworked layout to feature single event, separating out videos.

**Comment by adaaaam** [comment]
I can't see the screenshot...

**Comment by aileenrose** [comment]
> I can't see the screenshot...
on staging site:  https://deploy-preview-1016--sourcegraph.netlify.app/events/

**Pull request merged**
