### PR TITLE
Successful search sessions <> week 1 retention learnings

### PR DESCRIPTION
**Pull request by ebrodymoore**
You guys agree with this summary and conclusion(s)?

### CODE REVIEW

**Comment by ebrodymoore** [comment]
cc @macraig there's some interesting code intel takeaways here

**Review by malomarrec — COMMENTED** [review]
Generally agree, but we should try and avoid getting into a set definition of search sucesss that does not actually represent success. 
If an assumption is that users need the search tour, it means that they need help learning the syntax to get the results they want, which means that they could get better results with more syntax, which means their previous sessions were unsuccessful. 

**Suggestion** Use wording such as "proxy for search success" or clarify that the current definition only captures a part of search success.

**Review by malomarrec — COMMENTED** [review]
It'd be nice to always have
P(success | action) and P(success | not action)

**Review by malomarrec — APPROVED** [review]
It'd be nice to always have
P(success | action) and P(success | not action)

**Comment by ebrodymoore** [comment]
Thanks Malo. Added some clarifications to reflect all this

**Pull request merged**
