### PR TITLE
Fix pricing discrepancies

### PR DESCRIPTION
**Pull request by francisschmaltz**
Change pricing on site from old references of $5 a month to $4 a month.

### CODE REVIEW

**Comment by francisschmaltz** [comment]
Resolves https://github.com/sourcegraph/about/issues/6

**Comment by francisschmaltz** [comment]
@dadlerj CC'd you on this, but I'll merge once the checks pass.

**Comment by dadlerj** [comment]
Thanks! Was it intentional add the phabricator.png file here?

**Comment by francisschmaltz** [comment]
Yep! For Sourcegraph.com Homepage. This should have already existed though

**Comment by dadlerj** [comment]
Cool! (Just to be clear, though, it WAS only added in this specific PR. As long as that was intentional/expected we're good though.)

**Pull request merged**
