### PR TITLE
Gopls talk by Rebecca Stambler

### PR DESCRIPTION
**Pull request by axiomista**

### CODE REVIEW

**Comment by ryan-blunden** [comment]
Thanks @axiomista, reviewing now.

**Comment by axiomista** [comment]
@ryan-blunden if you'd like I can augment with images and push another commit. Do you think it would be helpful?

**Comment by ryan-blunden** [comment]
Yeah that sounds good.

Also, replace `$LIVEBLOGGER_NAME`.

**Comment by axiomista** [comment]
Thanks! Thought I did.

**Pull request merged**
