### PR TITLE
Separate KRs and KR results with full stops.

### PR DESCRIPTION
**Pull request by nicksnyder**
This makes them more readable.

See https://github.com/sourcegraph/about/pull/419#discussion_r352903788 for an example.

If approved I would update all existing OKRs to the new format before merging.

### CODE REVIEW

**Comment by christinaforney** [comment]
I just updated the product section in the Q4 OKRs to reflect a change that GitLab has adopted: https://github.com/sourcegraph/about/pull/421 I would suggest we adopt this format as well.

**Comment by nicksnyder** [comment]
Even better! I think we should update our documentation and OKRs in a single commit (either my PR or yours).

**Comment by christinaforney** [comment]
I can add it to mine if you like this strategy!

**Comment by nicksnyder** [comment]
Go for it. I'll close this PR.

**Pull request closed without merging**
