### PR TITLE
Use '@sourcegraph/event-logger' npm package for telemetry

### PR DESCRIPTION
**Pull request by erzhtor**
Part 3 of https://github.com/sourcegraph/sourcegraph/issues/31486.

## Description
- This PR uses `@sourcegraph/event-logger` npm package instead of embeddable script.
- Also `ViewStaticPage` event includes page **path** and **UTM markers** in `argument`/`publicArgument` fields
  - UTM markers are stripped on initial load, similar to sourcegraph web
## How to test
- `yarn install`
- `yarn --cwd ./website start`
- Open any page and make sure "ViewSaticPage" event is sent

### CODE REVIEW

**Review by bretthayes — CHANGES_REQUESTED** [review]
Cool! Tested and working. ✅  We just need to publish `@sourcegraph/event-logger` and add it as a dependency here before merging. Otherwise it'll break the site on merge when it's deployed.

**Comment by erzhtor** [comment]
> Cool! Tested and working. ✅ We just need to publish `@sourcegraph/event-logger` and add it as a dependency here before merging. Otherwise it'll break the site on merge when it's deployed.

Thanks for the reviews! Published `@sourcegraph/event-logger` and it as added dependency here.

**Comment by bretthayes** [comment]
> > Cool! Tested and working. ✅ We just need to publish `@sourcegraph/event-logger` and add it as a dependency here before merging. Otherwise it'll break the site on merge when it's deployed.
> 
> Thanks for the reviews! Published `@sourcegraph/event-logger` and it as added dependency here.

No worries! Just installed and tested. The dev server failed with the following:

```
Generating development JavaScript bundle failed
Unexpected token (10:20)
File: node_modules/@sourcegraph/event-logger/src/index.js:10:20
```

However the production build after running `yarn build && yarn serve` works. Weird! 🤔

**Comment by erzhtor** [comment]
> No worries! Just installed and tested. The dev server failed with the following:
> 
> ```
> Generating development JavaScript bundle failed
> Unexpected token (10:20)
> File: node_modules/@sourcegraph/event-logger/src/index.js:10:20
> ```
> 
> However the production build after running `yarn build && yarn serve` works. Weird! 🤔

Thanks for catching. Looks like, gatsby dev doesn't support eventLogger JS syntax, since it was not transpiled. Probably, the gatsby build uses a different config. Created PR updating eventLogger https://github.com/sourcegraph/eventlogger/pull/5

**Comment by erzhtor** [comment]
Hey, @bretthayes! I've updated and released a [patch version of eventlogger](https://github.com/sourcegraph/eventlogger/pull/5#issuecomment-1054605188). Tested locally, working correctly! I would appreciate it if you could take a look again, please.

**Review by bretthayes — APPROVED** [review]
Beautiful! Tested and working on dev and build. Great work! Let's ship it! 🚀

**Pull request merged**
