### PR TITLE
Update Code Intel roadmap

### PR DESCRIPTION
**Pull request by macraig**
Updated roadmap items after 3.22 planning and added Code Intel Gantt chart section

### CODE REVIEW

**Review by christinaforney — APPROVED** [review]
Looks good, feel free to merge as is. One concern is that there are a lot of things in progress, and many are very long efforts. What are the plans for breaking these down into smaller more focused efforts?

**Comment by Strum355** [comment]
Cant seem to be able to view the code intel section in the gantt chart on my side. Is that just me?

**Comment by christinaforney** [comment]
> Cant seem to be able to view the code intel section in the gantt chart on my side. Is that just me?

Hmmm, yeah the preview (https://deploy-preview-1786--sourcegraph.netlify.app/handbook/product/roadmap) isn't rendering that row. @macraig were you able to get this working locally? This can happen if mermaid gets grumpy about the formatting of one of your items. Try removing/commenting out to figure out the offender.

**Comment by macraig** [comment]
> Looks good, feel free to merge as is. One concern is that there are a lot of things in progress, and many are very long efforts. What are the plans for breaking these down into smaller more focused efforts?

@christinaforney we do have issue breakdowns for each of these but it seemed a bit too task-oriented for a roadmap. I will work on finding a middle ground granularity where we have smaller efforts labeled in a more product-oriented way.

> Cant seem to be able to view the code intel section in the gantt chart on my side. Is that just me?

Hmm the preview link seems to be rendering the old version of the whole file (if you see below, the Code Intel item list is also the old version) and there's none of the new Gantt chart code. I'm not sure what's happening there, I've opened the new version of the file in https://github.com/sourcegraph/about/blob/169cd93918b25c5584f68c8924648bb6b8fcb0ec/handbook/product/roadmap.md and I'm able to visualize the chart correctly in my editor... @Strum355 could you confirm? I don't think mermaid renders the preview in GitHub though (but this may be a misunderstanding on my side)

**Comment by christinaforney** [comment]
I just confirmed it worked for me locally - sorry I missed that the netlify was out of date! It does not render mermaid in GitHub, only when deploying the docsite.

>  we do have issue breakdowns for each of these but it seemed a bit too task-oriented for a roadmap. I will work on finding a middle ground granularity where we have smaller efforts labeled in a more product-oriented way.

Sounds good!

**Pull request merged**
