### PR TITLE
GopherCon 2019 Liveblog - Death by 3k timers

### PR DESCRIPTION
**Pull request by theclapp**

### CODE REVIEW

**Comment by ChrisHines** [comment]
I see this post has been merged, but the article does not appear on the blog page: https://about.sourcegraph.com/go/. Any estimate on when it will get posted?

**Comment by theclapp** [comment]
I've created https://github.com/sourcegraph/about/pull/202 to mark this and two other entries as published.  @ryan-blunden will have to merge it, of course.

**Comment by theclapp** [comment]
@ryan-blunden has pushed code to publish this entry.  All done!  :)

**Comment by theclapp** [comment]
BTW thanks, @ryan-blunden !

**Pull request merged**
